import type { ArticleImage } from '@/types';

/**
 * Hero photos for the articles, one per slug.
 *
 * Every photo is openly licensed (CC BY, CC0 or public domain), found through
 * Openverse, and credited on the page as its licence requires. Share-alike
 * and non-commercial licences were left out on purpose, so no photo carries
 * conditions beyond a credit line.
 *
 * Files live in /public/articles: `<slug>.webp` for the article page (as
 * wide as the original allows, up to 1600px) and `<slug>-sm.webp` at 640px
 * for cards. Both are cropped to 16:9.
 */
export const ARTICLE_IMAGES: Record<string, ArticleImage> = {
  'ai-in-internal-audit': {
    alt: "A hand on a laptop trackpad, reviewing a set of financial statements on screen",
    width: 1024,
    height: 576,
    credit: "InstructionalSolutions",
    creatorUrl: "https://www.flickr.com/photos/154958442@N02",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/154958442@N02/37315250442",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'applied-ai-indian-businesses-thesis': {
    alt: "Racks of servers in a data centre",
    width: 1024,
    height: 576,
    credit: "NeoSpire",
    creatorUrl: "https://www.flickr.com/photos/39131599@N06",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/39131599@N06/3595638270",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'bike-taxis-india-regulation': {
    alt: "A motorbike rider in a helmet carrying a pillion passenger through city traffic",
    width: 1024,
    height: 576,
    credit: "koadmunkee",
    creatorUrl: "https://www.flickr.com/photos/29946035@N08",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/29946035@N08/4580142408",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'building-an-ai-clone-of-myself': {
    alt: "A studio microphone with a pop filter in a recording booth",
    width: 1024,
    height: 576,
    credit: "audiomixhouse",
    creatorUrl: "https://www.flickr.com/photos/109949787@N03",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/109949787@N03/13430490054",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'byjus-lessons-for-investors': {
    alt: "A laptop keyboard beside a closed hardback book, in black and white",
    width: 1024,
    height: 576,
    credit: "dejankrsmanovic",
    creatorUrl: "https://www.flickr.com/photos/155403590@N07",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/155403590@N07/33207130558",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'construction-equipment-rental-india': {
    alt: "A yellow JCB backhoe loader parked on a roadside",
    width: 1024,
    height: 576,
    credit: "Matthew Paul Argall",
    creatorUrl: "https://www.flickr.com/photos/79157069@N03",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/79157069@N03/46119344355",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'ev-cab-fleet-unit-economics-tier-2-india': {
    alt: "Bajaj auto-rickshaw taxis lined up at a stand on a street in Goa",
    width: 1024,
    height: 576,
    credit: "andreboeni",
    creatorUrl: "https://www.flickr.com/photos/65344061@N06",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/65344061@N06/16253248664",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'ev-charging-infrastructure-india': {
    alt: "Charging cables plugged into an electric car at a public charger",
    width: 1023,
    height: 575,
    credit: "Ivan Radic",
    creatorUrl: "https://www.flickr.com/photos/26344495@N05",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/26344495@N05/51287497645",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'global-capability-centres-india': {
    alt: "Bagmane Tech Park in Bengaluru lit up at night and reflected in a lake",
    width: 1280,
    height: 720,
    credit: "Ajith Kumar from Bangalore, India",
    creatorUrl: "https://www.flickr.com/people/36008503@N03",
    source: 'Wikimedia Commons',
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=35626724",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'india-ev-adoption-two-three-wheelers': {
    alt: "Electric rickshaws carrying passengers in traffic in Aligarh, Uttar Pradesh",
    width: 1280,
    height: 720,
    credit: "N. Vivekananthamoorthy",
    source: 'Wikimedia Commons',
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=185657350",
    license: 'CC BY 4.0',
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
  'india-logistics-cost-gdp': {
    alt: "Container cranes and a loaded container ship at a port terminal",
    width: 1024,
    height: 576,
    credit: "yuukin",
    creatorUrl: "https://www.flickr.com/photos/78181498@N08",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/78181498@N08/6849736674",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'indian-restaurant-economics': {
    alt: "The shopfront of Kesar da Dhaba, a century-old eatery in Amritsar",
    width: 1024,
    height: 576,
    credit: "shankar s.",
    creatorUrl: "https://www.flickr.com/photos/77742560@N06",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/77742560@N06/39089536611",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'indian-startup-funding-2025': {
    alt: "Glass office buildings in Bengaluru against an orange evening sky",
    width: 1024,
    height: 576,
    credit: "mojosaurus",
    creatorUrl: "https://www.flickr.com/photos/77727541@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/77727541@N00/2986812192",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'indian-wedding-industry-breakdown': {
    alt: "A wedding ceremony under a mandap decorated with marigold garlands",
    width: 1024,
    height: 576,
    credit: "meg and rahul",
    creatorUrl: "https://www.flickr.com/photos/99689885@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/99689885@N00/3600676",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'investment-memo-blinkit-public-data': {
    alt: "A vegetable vendor's stall stacked with onions and potatoes, lit by bare bulbs",
    width: 1024,
    height: 576,
    credit: "the_steve_cox",
    creatorUrl: "https://www.flickr.com/photos/35468147898@N01",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/35468147898@N01/69607921",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'leaving-big-4-for-a-startup': {
    alt: "Office towers of Cyber City in Gurugram beside a busy highway",
    width: 1024,
    height: 576,
    credit: "Ninara",
    creatorUrl: "https://www.flickr.com/photos/37583176@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/37583176@N00/49294223888",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'marketplace-metrics-due-diligence': {
    alt: "A person reviewing printed charts at a desk beside a laptop and a coffee",
    width: 1023,
    height: 575,
    credit: "Semtrio",
    creatorUrl: "https://www.flickr.com/photos/163837264@N07",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/163837264@N07/43291332124",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'numbers-i-can-defend': {
    alt: "A calculator and pen resting on a paper ledger",
    width: 1024,
    height: 576,
    credit: "seniorplanning",
    creatorUrl: "https://www.flickr.com/photos/126131780@N08",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/126131780@N08/14877276186",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'one-page-monthly-update': {
    alt: "A desk seen from above with a newspaper, a calculator, a laptop and a phone",
    width: 1024,
    height: 576,
    credit: "Homedust",
    creatorUrl: "https://www.flickr.com/photos/159630537@N08",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/159630537@N08/40924421560",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'open-networks-mobility-namma-yatri': {
    alt: "Auto-rickshaws on a tree-lined road in Bengaluru",
    width: 1024,
    height: 576,
    credit: "Melanie-m",
    creatorUrl: "https://www.flickr.com/photos/84295554@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/84295554@N00/2674142420",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'pricing-services-business-playbook': {
    alt: "Two people shaking hands across a meeting table",
    width: 1024,
    height: 576,
    credit: "Rawpixel Ltd",
    creatorUrl: "https://www.flickr.com/photos/147875007@N03",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/147875007@N03/45739298092",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'push-and-absorb-framework': {
    alt: "Railway tracks crossing and branching at a set of points",
    width: 1024,
    height: 576,
    credit: "Prayitno",
    creatorUrl: "https://www.flickr.com/photos/34128007@N04",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/34128007@N04/4391337886",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'quick-commerce-india-economics': {
    alt: "A delivery partner riding a scooter on a city street in Bengaluru",
    width: 1280,
    height: 720,
    credit: "SerChevalerie",
    creatorUrl: "https://commons.wikimedia.org/wiki/User:SerChevalerie",
    source: 'Wikimedia Commons',
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=181504090",
    license: 'CC0 1.0',
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  'reliability-as-growth-strategy': {
    alt: "An Indian Railways diesel locomotive pulling a passenger train",
    width: 1024,
    height: 576,
    credit: "Smeet Chowdhury",
    creatorUrl: "https://www.flickr.com/photos/50628848@N07",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/50628848@N07/7080920345",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'religious-tourism-india-economy': {
    alt: "Priests performing the evening Ganga aarti with lamps in Varanasi",
    width: 1024,
    height: 576,
    credit: "Arian Zwegers",
    creatorUrl: "https://www.flickr.com/photos/67769030@N07",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/67769030@N07/6296002701",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'running-an-agency-in-college': {
    alt: "Students working at laptops around tables in a studio classroom",
    width: 1023,
    height: 575,
    credit: "vancouverfilmschool",
    creatorUrl: "https://www.flickr.com/photos/38174668@N05",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/38174668@N05/4346159065",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'sizing-cab-market-tier-2-city': {
    alt: "A busy street in Madurai with shops, traffic and a temple tower in the distance",
    width: 1024,
    height: 576,
    credit: "mckaysavage",
    creatorUrl: "https://www.flickr.com/photos/56796376@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/56796376@N00/1814268800",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'tier-2-india-investment-thesis': {
    alt: "The Jammu Tawi Express standing at a station platform",
    width: 1024,
    height: 576,
    credit: "Smeet Chowdhury",
    creatorUrl: "https://www.flickr.com/photos/50628848@N07",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/50628848@N07/7197829988",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'upi-payments-india-economics': {
    alt: "A hand holding a phone showing a QR code for payment",
    width: 1024,
    height: 576,
    credit: "markus119",
    creatorUrl: "https://www.flickr.com/photos/35850894@N08",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/35850894@N08/50125234728",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'voice-of-customer-loops-retention': {
    alt: "A customer feedback terminal with rating buttons on a counter",
    width: 1024,
    height: 576,
    credit: "Kai Hendry",
    creatorUrl: "https://www.flickr.com/photos/16105436@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/16105436@N00/3912162900",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'weekly-operating-review-kpi-cadence': {
    alt: "A small team working through notes on a whiteboard in a meeting",
    width: 1024,
    height: 576,
    credit: "kevin dooley",
    creatorUrl: "https://www.flickr.com/photos/12836528@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/12836528@N00/7007372665",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'where-margin-leaks-indian-companies': {
    alt: "A close-up of an Indian two-rupee coin",
    width: 1024,
    height: 576,
    credit: "Autherous",
    creatorUrl: "https://www.flickr.com/photos/46627377@N00",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/46627377@N00/4720303186",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
  'zero-commission-shift-push-and-absorb': {
    alt: "The view from the back seat of an auto-rickshaw, looking past the driver at the road",
    width: 1024,
    height: 576,
    credit: "Jorge Lascar",
    creatorUrl: "https://www.flickr.com/photos/8721758@N06",
    source: 'Flickr',
    sourceUrl: "https://www.flickr.com/photos/8721758@N06/5440497900",
    license: 'CC BY 2.0',
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
  },
};

export const articleImage = (slug: string): ArticleImage | undefined => ARTICLE_IMAGES[slug];

/** Public paths for an article's photo. */
export const articleImageSrc = (slug: string) => ({
  full: `/articles/${slug}.webp`,
  small: `/articles/${slug}-sm.webp`,
});
