import type { TimelineMilestone } from '@/types';

/** Chronological, oldest first. Figures are from the CV. */
export const timeline: TimelineMilestone[] = [
  {
    id: 'dps-jammu',
    year: '2007 — 2021',
    title: 'School',
    org: 'Delhi Public School',
    location: 'Jammu, India',
    kind: 'education',
    summary: 'Fourteen years in Jammu, and the first taste of leading something.',
    details: [
      'CBSE Class XII: 92%, Commerce with Maths.',
      'CBSE Class X: 94.2%, including 100/100 in Science — top 5 out of 600 students.',
      'House Captain, selected from a cohort of 600+.',
      'Fourth generation of a Jammu business family, so cash flow and customers were dinner-table conversation long before they were coursework.',
    ],
  },
  {
    id: 'symbiosis',
    year: '2021 — 2024',
    title: 'BBA, Accounts & Finance and Marketing',
    org: 'Symbiosis Centre for Management Studies',
    location: 'Pune, India',
    kind: 'education',
    summary: 'Where the commercial instinct from a business family met actual frameworks.',
    details: [
      'CGPA 8.16, top 10% of the batch.',
      'Elected Placement Coordinator from a cohort of 400 students.',
      'Marketing Head at Sympulse; active with Enactus Pune.',
      'Started taking on real client work in my second year rather than waiting for the degree to end.',
    ],
  },
  {
    id: 'cairros',
    year: '2022 — 2024',
    title: 'Founder & Managing Partner',
    org: 'Cairros',
    location: 'Pune, India',
    kind: 'venture',
    summary: 'Built a consulting and marketing agency to seven-figure revenue while still at college.',
    details: [
      'Scaled to seven-figure annual revenue in two years, owning strategy, sales and delivery end to end.',
      'Grew three restaurant clients 30% in revenue at 7% month on month.',
      'Raised a magazine client’s sales 3.5x — ₹2L to ₹7L a month at 23% MoM over six months.',
      'Expanded across four sectors via rebrand, hiring and growth mandates.',
    ],
  },
  {
    id: 'equip9',
    year: '2022 — 2024',
    title: 'Digital Marketing Executive',
    org: 'Equip9',
    location: 'Pune, India',
    kind: 'work',
    summary: 'Segmentation-led acquisition for a construction-tech marketplace.',
    details: [
      'Improved lead conversion 40% and drove 300% profit growth through segmentation-led acquisition.',
      'Generated ₹30L+ in annual revenue owning branding and delivery for 15+ accounts.',
      'Halved content production turnaround by building a content engine and AI workflow agents.',
    ],
  },
  {
    id: 'pwc',
    year: '2024 — 2026',
    title: 'Risk Consulting Specialist 2',
    org: 'PwC India',
    location: 'Gurugram, India',
    kind: 'work',
    summary: 'Fifteen months of Big-4 rigour — diagnostics, process redesign and ₹6+ Cr in client savings.',
    details: [
      'Delivered ₹6+ Cr in annual client cost savings via root-cause diagnostics and process redesign.',
      'Realised ₹2 Cr+ by reengineering 25+ processes across procurement, HR and finance.',
      'Saved 10,000+ consulting hours across 200+ consultants by co-developing an internal audit AI tool.',
      'Executed engagements worth ₹12 Cr+ for 10+ clients including Cars24, Stryker India and PIF.',
      'Promoted from Specialist to Specialist 2 inside a year.',
    ],
  },
  {
    id: 'mccs',
    year: '2024 — 2025',
    title: 'Business Transformation Consultant',
    org: 'MCCS Infra',
    location: 'India',
    kind: 'work',
    summary: 'Manpower restructuring and a digital front door for an infrastructure business.',
    details: [
      'Unlocked ₹2 Cr in cost savings via manpower restructuring and capacity planning.',
      'Accelerated inbound enquiries 4.5x through digital strategy and a brand overhaul.',
      'Compressed hiring turnaround 80% and halved cost per hire.',
    ],
  },
  {
    id: 'zencabs',
    year: '2026 — Present',
    title: 'Head of Strategy & Growth',
    org: 'ZenCabs',
    location: 'Jammu, India',
    kind: 'venture',
    summary: 'An EV mobility venture from launch to 25,000+ users and ₹3 Cr annualised in four months.',
    details: [
      'Built the venture from launch to 25,000+ users and a ₹3 Cr annualised run-rate in four months.',
      'Grew monthly GMV past ₹25L across 7,500+ rides at ₹331 AOV.',
      'Cut ride cancellations from 40% to 6% by institutionalising 10+ SOPs.',
      'Lifted fleet utilisation from 40% to 75%, tracked against 15+ KPIs in weekly founder reviews.',
      'Onboarded 43 driver partners and grew the fleet to 40 cars in three months.',
    ],
  },
  {
    id: 'shaadi-mangalam',
    year: '2026 — Present',
    title: 'Growth & Business Strategy Consultant',
    org: 'Shaadi Mangalam',
    location: 'India',
    kind: 'venture',
    summary: 'Pricing and sales restructure for a wedding services business.',
    details: [
      'Tripled monthly leads to 3,000 and lifted conversion from 1.4% to 4%.',
      'Shipped 100+ process and product fixes across sprints, leading the website redesign.',
    ],
  },
  {
    id: 'masters-union',
    year: '2026 — Present',
    title: 'PGP in Technology & Business Management',
    org: 'Masters’ Union',
    location: 'Gurugram, India',
    kind: 'education',
    summary: 'Adding the technology layer to a consulting and operating background.',
    details: [
      'Pursuing the PGP TBM — the deliberate step from business operator toward technology builder.',
      'I had spent three years shipping growth, consulting and operations work; the gap was building the thing itself.',
      'Masters’ Union is practitioner-taught, which suits how I actually learn: do it, then understand why it worked.',
    ],
  },
];
