// GENERATED by scripts/write-model-manifest.mjs — do not edit.
//
// Each URL carries a hash of the file's bytes so that the year-long
// `immutable` cache header on /models/* stays truthful: replacing a model
// changes its URL, so browsers fetch it instead of serving a stale copy.

export const MODEL_URLS = {
  /** archit.glb — 1.98MB */
  archit: '/models/archit.glb?v=944015f8',
  /** macbook.glb — 2.90MB */
  macbook: '/models/macbook.glb?v=a62912b8',
} as const;

export type ModelKey = keyof typeof MODEL_URLS;
