// GENERATED by scripts/write-model-manifest.mjs — do not edit.
//
// Each URL carries a hash of the file's bytes so that the year-long
// `immutable` cache header on /models/* stays truthful: replacing a model
// changes its URL, so browsers fetch it instead of serving a stale copy.

export const MODEL_URLS = {
  /** archit.glb — 2.55MB */
  archit: '/models/archit.glb?v=a55a00e3',
  /** macbook.glb — 2.89MB */
  macbook: '/models/macbook.glb?v=392e7b13',
} as const;

export type ModelKey = keyof typeof MODEL_URLS;
